// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CrdtOperation } from "./CrdtOperation";

export type SyncV2Request = { clock: bigint, device_id: string, since_clock: bigint | null, operations: Array<CrdtOperation>, };
