// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CrdtOperation } from './CrdtOperation';

export interface SyncResponse {
  clock: bigint;
  operations: CrdtOperation[];
}
