// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface TabData {
  window_id: string;
  url: string;
  title: string;
  active: boolean;
  index: number;
  updated_at: bigint;
}
