// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Tab {
  id: string;
  windowId: string;
  url: string;
  title: string;
  active: boolean;
  index: bigint;
  updatedAt: number;
}
