// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Window {
  id: string;
  tracked: boolean;
  tabCount: bigint;
  updatedAt: number;
}
