// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorCode } from './ErrorCode';

/**
 * Detailed error information
 */
export interface ErrorDetail {
  id: string;
  code: ErrorCode;
  message: string;
  timestamp: string;
  source: string | null;
}
