// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorDetail } from './ErrorDetail';
import type { RetryInfo } from './RetryInfo';

/**
 * Error response structure for HTTP APIs
 */
export interface ErrorResponse {
  status: string;
  error: ErrorDetail;
  retry: RetryInfo | null;
}
