# Tanaka Server Configuration Example
# Copy this file to tanaka.toml and customize for your setup

[server]
# Bind address for the server
bind_addr = "127.0.0.1:8443"
# Worker threads (optional, defaults to CPU count)
# worker_threads = 4
# Request timeout in seconds
request_timeout_secs = 30

[database]
# Database URL (SQLite example)
url = "sqlite://tanaka.db"
# Maximum database connections
max_connections = 5
# Connection timeout in seconds
connection_timeout_secs = 10

[auth]
# Shared authentication token (REQUIRED - must match extension config)
shared_token = "your-secret-token-here"
# Token header name
token_header = "Authorization"
# Enable rate limiting
rate_limiting = true
# Max requests per minute per IP
max_requests_per_minute = 60

# TLS configuration (optional - uncomment to enable HTTPS)
# [tls]
# cert_path = "/path/to/cert.pem"
# key_path = "/path/to/key.pem"

[sync]
# Polling interval in seconds
poll_secs = 5
# Database flush interval in seconds
flush_secs = 5
# Maximum sync payload size in bytes
max_payload_size = 1048576 # 1MB
# Enable compression (experimental)
compression = false

[logging]
# Log level (trace, debug, info, warn, error)
level = "info"
# Log format (json, pretty, compact)
format = "pretty"
# Enable request logging
request_logging = true
