// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TabData } from './TabData';

export type CrdtOperation =
  | { type: 'upsert_tab'; id: string; data: TabData }
  | { type: 'close_tab'; id: string; closed_at: bigint }
  | { type: 'set_active'; id: string; active: boolean; updated_at: bigint }
  | { type: 'move_tab'; id: string; window_id: string; index: number; updated_at: bigint }
  | { type: 'change_url'; id: string; url: string; title: string | null; updated_at: bigint }
  | { type: 'track_window'; id: string; tracked: boolean; updated_at: bigint }
  | { type: 'untrack_window'; id: string; updated_at: bigint }
  | { type: 'set_window_focus'; id: string; focused: boolean; updated_at: bigint };
