// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CrdtOperation } from './CrdtOperation';

export interface SyncRequest {
  clock: bigint;
  device_id: string;
  since_clock: bigint | null;
  operations: CrdtOperation[];
}
