name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup all required tools
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - uses: pnpm/action-setup@v4
        with:
          version: 10.11.0

      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "pnpm"
          cache-dependency-path: extension/pnpm-lock.yaml

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      # Cache all dependencies
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pre-commit
            ~/.cargo/registry
            ~/.cargo/git
            server/target
            extension/node_modules
          key: ${{ runner.os }}-deps-${{ hashFiles('.pre-commit-config.yaml', '**/Cargo.lock', '**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      # Install dependencies in parallel
      - name: Install all dependencies
        run: |
          echo "Installing extension dependencies..."
          (cd extension && pnpm install --frozen-lockfile --prefer-offline) &

          echo "Fetching Rust dependencies..."
          (cd server && cargo fetch) &

          # Wait for both to complete
          wait

      # TypeScript types are now committed to the repository
      # No generation step needed - this saves ~2-3 minutes in CI

      # Run pre-commit
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files
        env:
          # Skip hooks that don't make sense in CI
          SKIP: no-commit-to-branch
