name: Code Quality

on:
  pull_request:
  push:
    branches: [main]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Cache pre-commit environments for faster runs
      - name: Cache pre-commit
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit-${{ runner.os }}-

      # Install Node.js for TypeScript checks
      - uses: actions/setup-node@v4
        with:
          node-version: "24"

      # Install pnpm for TypeScript checks
      - uses: pnpm/action-setup@v4
        with:
          version: 10.11.0

      # Install extension dependencies
      - name: Install extension dependencies
        run: |
          cd extension
          pnpm install --frozen-lockfile

      # Install Rust for Rust checks
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      # Build Rust dependencies (needed for type generation)
      - name: Build Rust dependencies
        run: |
          cd server
          cargo build

      # Generate TypeScript types from Rust models
      - name: Generate TypeScript types
        run: |
          python3 scripts/tanaka.py generate

      # Run pre-commit
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files
